apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bravo-multipais-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: bravo-multipais.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bravo-multipais-svc
                port:
                  number: 80