apiVersion: v1
kind: Service
metadata:
  name: bravo-multipais-svc
spec:
  selector:
    app: bravo-multipais
    component: web 
  type: ClusterIP
  ports:
    - name: http
      port: 80          # puerto dentro del cluster
      targetPort: 4000  # puerto interno del contenedor