apiVersion: v1
kind: ConfigMap
metadata:
  name: bravo-multipais-config
data:
  URL_HOST: "bravo-multipais.example.com"
  URL_SCHEME: "https"
  URL_PORT: "443"

  POOL_SIZE: "10"
  ECTO_IPV6: "false"

  DNS_CLUSTER_QUERY: "bravo-multipais-headless.default.svc.cluster.local"

  SKIP_WEBHOOKS: "false"
  WEBHOOK_URL: "https://mi-consumidor-externo.com/webhooks/applications"