apiVersion: v1
kind: Secret
metadata:
  name: bravo-multipais-secrets
type: Opaque
stringData:
  # Formatoecto://USER:PASS@HOST:PORT/DB
  DATABASE_URL: "ecto://user:password@postgres:5432/bravo_multipais_prod"

  # mix phx.gen.secret
  SECRET_KEY_BASE: "PON_AQUI_UNA_SECRET_KEY_BASE_REAL"