global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bravo_multipais"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:4000"]